### ISSUE TITLE
特殊字符 \/:*?"<>| 导致windows下无法重命名

### ISSUE THREAD

**Issue by ximu3** [nuthx/bangumi-autorenamer#12]
有些动漫名包含\/:*?"<>|，在windows下无法重命名，希望程序可以过滤掉这些字符。
:D

**Comment by nuthx** [comment]
包含特殊字符的动画重命名出现在哪一步骤？
程序处理时已经排除了特殊字符，可能还有遗漏
能否提供一个bgm id和原始文件名，方便我排查一下

**Comment by ximu3** [comment]
bgm id：274646
原始文件名：Princess Connect! Re Dive Season 2
目标文件名：[2020-04] プリンセスコネクト！Re:Dive [01] [274646]
现象：点击重命名无反应
![bgmrm_pr](https://pan.timero.xyz/d/onedrive/img_lib_001/bgm_pr.gif)
