### ISSUE TITLE
能否添加对文件的重命名？

### ISSUE THREAD

**Issue by 99Mr-Z** [nuthx/bangumi-autorenamer#15]
将视频文件（MP4、MKV）、音轨文件（MKA、FALC）、字幕文件（ASS）这些文件也进行重命名，后面添加上标记对应的剧集标号

**Comment by nuthx** [comment]
没有计划加入文件命名功能，BangumiRenamer 只会处理文件夹本身
可以尝试用一个 Python 脚本，或 [Rename](https://www.den4b.com/products/renamer) 组合来重命名文件
给一个思路，抛砖引玉：
1. 用 BangumiRenamer 重命名好文件夹，插入一个字符串代替后续要改为集数的数字，例如 `_NUM_`
2. 分批拖入视频、音轨、字幕，排序，然后重命名为父文件夹名
3. 将文件名中的 `_NUM_` 更改为数字序列，完成重命名
4. 手动删除父文件夹的 `_NUM_`

**Comment by 99Mr-Z** [comment]
> 没有计划加入文件命名功能，BangumiRenamer 只会处理文件夹本身 可以尝试用一个 Python 脚本，或 [Rename](https://www.den4b.com/products/renamer) 组合来重命名文件 给一个思路，抛砖引玉：
> 
> 1. 用 BangumiRenamer 重命名好文件夹，插入一个字符串代替后续要改为集数的数字，例如 `_NUM_`
> 2. 分批拖入视频、音轨、字幕，排序，然后重命名为父文件夹名
> 3. 将文件名中的 `_NUM_` 更改为数字序列，完成重命名
> 4. 手动删除父文件夹的 `_NUM_`

实际上目前已经将文件夹进行重命名了，只是想看看有没有更好的方案进一步的简化操作，尽可能的自动化，部分进行人工矫正即可，不过仍然感谢提供新的思路
