### ISSUE TITLE
QPushButton(icon: QIcon, text: str, parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'MyMainWindow'

### ISSUE THREAD

**Issue by 0xgejutaixiao** [nuthx/bangumi-autorenamer#17]
self.newVersionButton = PrimaryPushButton("有新版本", self, FluentIcon.LINK)
错误
发生异常: TypeError
arguments did not match any overloaded call:
  QPushButton(parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'MyMainWindow'
  QPushButton(text: str, parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'MyMainWindow'
  QPushButton(icon: QIcon, text: str, parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'MyMainWindow'

**Comment by 0xgejutaixiao** [comment]
windows 11

**Comment by nuthx** [comment]
是编译时出现的吗？PySide6-Fluent-Widgets版本是多少
