### ISSUE TITLE
建议打包mac应用不要用onefile（-F）方式

### ISSUE THREAD

**Issue by hyrulelinks** [nuthx/bangumi-autorenamer#19]
我看了下目录结构，猜测是用pyinstaller打包并选择了onefile（或-F）方式，这样打包虽然应用目录树结构简洁，只有一个可执行程序和一个图标，但启动效率非常低，因为启动时还需要先解压相关的数据到本地，再读取后启动，且每次启动都要经过这个过程，一开始我以为应用卡住了，多点了好几次，过了大概20秒后跳出了一堆应用窗口

建议打包时用-D选项，启动效率会比较正常

@nuthx

**Comment by nuthx** [comment]
目前macOS下启动的确慢的离谱，水平有限排查不出原因。已经尝试过-D编译，并没有解决问题
只有在运行dist/BangumiRenamer时才能秒开（而非dist/BangumiRenamer.app）

不过Windows下低配PC启动也不慢。方便告知一下你的系统和配置吗？

回到问题，由于Python目录形式编译后，生成的文件结构太乱，故没有计划采用-D选项
如果对启动速度比较敏感，可以修改build.spec后自行编译

**Comment by hyrulelinks** [comment]
```
# -*- mode: python ; coding: utf-8 -*-

version = "2.0.1"

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('src/style', 'src/style'), ('src/font', 'src/font'), ('src/image', 'src/image'), ('lib', 'lib')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Bangumi Renamer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['image/icon.icns'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Bangumi Renamer',
)
app = BUNDLE(
    coll,
    name='Bangumi Renamer.app',
    icon='image/icon.icns',
    bundle_identifier=None,
    info_plist={
        'CFBundleDisplayName': 'Bangumi Renamer',
        'CFBundleName': 'Bangumi Renamer',
        'CFBundlePackageType': 'APPL',
        'CFBundleSignature': 'BGRN',
        'CFBundleShortVersionString': version,
        'CFBundleVersion': version,
        'CFBundleExecutable': 'Bangumi Renamer',
        'CFBundleIconFile': 'icon.icns',
        'CFBundleIdentifier': 'dev.nuthx.bgrn',
        'CFBundleInfoDictionaryVersion': '6.0',
        'LSApplicationCategoryType': 'public.app-category.graphics-design',
        'LSEnvironment': {'LANG': 'zh_CN.UTF-8'},
        }
)
```

上面是我自己构建用的spec文件，构建好的应用在mac上秒开

onefile构建适合没有任何data和binary，纯源码的项目打包，这样每次运行不需要解压运行所需的资源文件
这个项目有不少非py脚本的资源文件，用onefile模式每次都要先解压到临时路径，每次启动都会有新的临时路径，垃圾文件一直在积累，启动速度非常感人，所以一般情况下不建议用onefile，除非项目就一个main.py

另外，PyQt（或pyside）写的图形程序启动本来就是偏慢的，属于正常情况，用python自带的tkinter就很快，但tkinter太丑了。另外有个tog库可以写python原生的Mac应用，但只能用beeware打包，不支持pyinstaller，启动速度也很快，但也没有qt漂亮，各有利弊

**Comment by hyrulelinks** [comment]
纯从技术上讲，mac应用用c语言写的大多只有一个可执行文件，且效率不低，python的onefile就效率低很多，但代码好写，各有利弊吧，python如果觉得项目太乱，也可以用beeware打包，结构会清爽不少，效率上和-D差不多，因为这个工具直接把运行需要的python直接打包进应用了，结构反而变简单了

**Comment by hyrulelinks** [comment]
哦，忘了回答了，我是M1 Max笔记本，内存32GB

**Comment by nuthx** [comment]
使用你提供的spec编译后，确实可以秒开了
不过体积似乎增大了不少（46MB→125MB），另外删除同时生成的BangumiRenamer文件夹好像也能运行？

另外，如果在macOS上采用目录形式编译，将app拖到“应用程序”时，是不是需要同时复制这个文件夹一起过去？

**Comment by hyrulelinks** [comment]
> 使用你提供的spec编译后，确实可以秒开了
> 不过体积似乎增大了不少（46MB→125MB），另外删除同时生成的BangumiRenamer文件夹好像也能运行？
> 
> 另外，如果在macOS上采用目录形式编译，将app拖到“应用程序”时，是不是需要同时复制这个文件夹一起过去？

不用，文件夹那个是用来调试的，不用管，只要后缀.app那个就好

把.app打成zip压缩包也是46mb，一样的，mac应用从dmg或zip解压出来后体积都会变大不少，正常现象，要减少体积需要在打包时排除应用独立运行不需要的库，但这个要一个个去试，太繁琐，我就没管了

**Comment by hyrulelinks** [comment]
目录形式只是.app里面的python库和资源文件等没有压缩到main可执行程序中，运行时不需要解压，所以效率会变高，外面那个文件夹是打包过程中用来调试bug的，一般情况下不用去管他

**Comment by nuthx** [comment]
> 目录形式只是.app里面的python库和资源文件等没有压缩到main可执行程序中，运行时不需要解压，所以效率会变高，外面那个文件夹是打包过程中用来调试bug的，一般情况下不用去管他

感谢解答，学习到了
