### ISSUE TITLE
可否添加硬链接功能

### ISSUE THREAD

**Issue by ZephyrLinD** [nuthx/bangumi-autorenamer#27]
RT，除了 PT 之外，也会给 BT 做种，更愿意保留原文件，硬链接来给类似 Emby 的媒体库进行入库

**Comment by Hyphen-H** [comment]
> RT，除了 PT 之外，也会给 BT 做种，更愿意保留原文件，硬链接来给类似 Emby 的媒体库进行入库

Movie pilot有类似功能

**Comment by nuthx** [comment]
感谢建议，目前暂时没有添加硬链接的计划
可以尝试[hlink](https://github.com/likun7981/hlink)来做硬链接，纯自动化操作 #9
