### ISSUE TITLE
希望能够加上链接模式

### ISSUE THREAD

**Issue by Lambholl** [nuthx/bangumi-autorenamer#9]
在`src/core.py`的第 563 行：
```python
os.rename(file_path, final_path_2)
```
对于保种来说，直接重命名并不是一个很好的选择，我认为采用符号链接会更好：
```python
os.symlink(file_path, final_path_2)  # 这种方式在Windows下可能会权限不足

subprocess.run(['mklink', '/j', final_path_2, file_path], shell=True)  # Windows
```
这样的话，需要同步修改第 561 行的`file_dir`，由于我不会用`Qt`另外加一个选项设置这个目录，因此无力`pr`，只能提出大致思路，希望能够被采纳。

另，Windows 下 Python 直接创建符号链接权限问题，可以参考[这里](https://www.jianshu.com/p/0e307bfe8770)
要解决的话，可以选择判断系统：
```python
if platform.system() != 'Windows':
    os.symlink(file_path, final_path_2)
else:
    subprocess.run(['mklink', '/j', final_path_2, file_path], shell=True)
```

**Comment by nuthx** [comment]
感谢建议，软硬链接的操作有一定风险，考虑到不同的操作系统以及权限配置，我目前的水平没办法妥善处理链接问题
其次，BangumiRenamer 只求做好重命名的工作，目前没有计划增加更高级的功能

个人始终认为专业的事情交给专业的软件
在保种的问题上，我选择 [hlink](https://github.com/likun7981/hlink) 处理下载的动画资源
相比符号链接，硬链接在番剧的管理上更加灵活，允许删除不需要的文件（Screenshots, MD5 等）而不影响源文件
推荐尝试一下

**Comment by Hyphen-H** [comment]
你可能在找：nastool
不过硬链接了的话，一般是要配合emby jellyfin等软件来做一个系统的管理
我觉得还是直接重命名吧 动漫压制对保种需求不像pt那么大
